### ISSUE TITLE
Logo Proposal 

### ISSUE THREAD

**Issue by Arslanshn** [daylog/daylog#1]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by sethvincent** [comment]
Hey! My plan is to use these emoji as a rough logo: ☀️📝

The first version could be something like we did with township: https://github.com/township

**Comment by sethvincent** [comment]
Closing this for now as the emoji plan is working as a bare minimum logo. Thanks for opening this!
